apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-static.fullname" . }}-config
  labels:
    {{- include "nginx-static.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }

      # block git and htaccess files
      location ~ /\.(git|ht) {
          deny all;
      }

      {{- if and (.Values.configNginx) (kindIs "string" .Values.configNginx) }}
      {{ .Values.configNginx | nindent 6 }}
      {{- end }}
    }
