apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "unifi.fullname" . }}
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "unifi.fullname" . }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "unifi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/version: {{ .Values.image.tag | default .Chart.AppVersion | quote }}
        {{- include "unifi.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "unifi.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostNetwork: {{ .Values.hostNetwork }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- with .Values.image }}
          image: "{{ .repository }}:{{ .tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: stun
              containerPort: 3478
              protocol: UDP
            - name: l2-discovery
              containerPort: 1900
              protocol: UDP
            - name: ap-discovery
              containerPort: 10001
              protocol: UDP
            - name: guest-https
              containerPort: 8843
              protocol: TCP
            - name: guest-http
              containerPort: 8880
              protocol: TCP
            - name: throughput
              containerPort: 6789
              protocol: TCP
            - name: syslog
              containerPort: 5514
              protocol: UDP
          livenessProbe:
            httpGet:
              path: /
              port: https
              scheme: HTTPS
          startupProbe:
            failureThreshold: 100
            periodSeconds: 3
            httpGet:
              path: /
              port: https
              scheme: HTTPS
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      nodeName: {{ .Values.nodeName }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if and (.Values.persistence.enabled) (.Values.persistence.existingClaim) }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
        {{- else if not .Values.persistence.enabled }}
        - name: config
          emptyDir: {}
  {{- else if and (.Values.persistence.enabled) (not .Values.persistence.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: config
        labels:
          {{ include "unifi.labels" . | nindent 10 }}
        {{- if .Values.persistence.annotations }}
        annotations:
          {{- toYaml .Values.persistence.annotations | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
          {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        storageClass: {{ .Values.persistence.storageClass }}
        {{- if .Values.persistence.selector }}
        selector:
          {{- toYaml .Values.persistence.selector | nindent 10 }}
        {{- end }}
  {{- end }}
