apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "fossology.fullname" . }}-config
  labels:
    {{- include "fossology.base.labels" . | nindent 4 }}
stringData:
  FOSSOLOGY_DB_HOST: {{ include "fossology.fullname" . }}-postgresql
  FOSSOLOGY_DB_NAME: {{ default "fossology" .Values.postgresql.auth.database | quote }}
  FOSSOLOGY_DB_USER: {{ default "fossy" .Values.postgresql.auth.username | quote }}
  FOSSOLOGY_DB_PASSWORD: {{ default "fossy" .Values.postgresql.auth.password | quote }}
