{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "fossology.pvcName" . }}
  labels:
    {{- include "fossology.web.labels" . | nindent 4 }}
spec:
{{- with .Values.persistence }}
  {{- with .accessModes }}
  accessModes:
    {{- toYaml . | nindent 6 }}
  {{- end }}
  resources:
    requests:
      storage: {{ .size }}
  storageClassName: {{ .storageClass | quote }}
{{- end }}
{{- end }}
