apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "fossology.fullname" . }}-scheduler
  labels:
    {{- include "fossology.scheduler.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "fossology.fullname" . }}-scheduler
  selector:
    matchLabels:
      {{- include "fossology.scheduler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.scheduler.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fossology.scheduler.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fossology.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.scheduler.podSecurityContext | nindent 8 }}
      containers:
        - name: scheduler
          securityContext:
            {{- toYaml .Values.scheduler.securityContext | nindent 12 }}
          {{- with .Values.image }}
          image: "{{ .repository }}:{{ .tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          args: [scheduler]
          envFrom:
            - secretRef:
                name: {{ include "fossology.fullname" . }}-config
          readinessProbe:
            tcpSocket:
              port: 24693
          ports:
            - name: scheduler
              containerPort: 24693
              protocol: TCP
          resources:
            {{- toYaml .Values.scheduler.resources | nindent 12 }}
      {{- with .Values.scheduler }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
