apiVersion: v1
kind: Service
metadata:
  name: {{ include "fossology.fullname" . }}-web
  labels:
    {{- include "fossology.web.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "fossology.web.selectorLabels" . | nindent 4 }}
{{- with .Values.web.service }}
  type: {{ .type }}
  ports:
    - port: {{ .port }}
      targetPort: http
      protocol: TCP
      name: http
{{- end }}
