apiVersion: v1
kind: Service
metadata:
  name: {{ include "errbot.fullname" . }}
  labels:
    {{- include "errbot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      appProtocol: http
  selector:
    {{- include "errbot.selectorLabels" . | nindent 4 }}
