apiVersion: v2
name: salt
type: application
description: Software to automate the management and configuration of any infrastructure or application at scale.
keywords:
  - configuration-management
  - infrastructure-management
  - cloud-management
  - event-management
  - remote-execution
  - infrastructure-automation
  - saltstack
home: https://github.com/midokura/helm-charts-community/tree/main/salt
icon: https://saltproject.io/images/logo.svg
sources:
  - https://github.com/saltstack/salt
  - https://gitlab.com/saltstack/open/saltdocker
maintainers:
  - name: David Girón
    url: https://github.com/duhow

version: 0.0.2
# renovate: datasource=docker depName=saltstack/salt
appVersion: "3006.3"

dependencies:
  - name: mariadb
    alias: mysql
    repository: https://charts.bitnami.com/bitnami
    version: 14.0.2
    condition: alcali.enabled, mysql.install
