apiVersion: v1
kind: Service
metadata:
  name: {{ include "dependency-track.fullname" . }}-frontend
  labels:
    {{- include "dependency-track.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dependency-track.frontend.selectorLabels" . | nindent 4 }}
