apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dependency-track.fullname" . }}-api
  labels:
    {{- include "dependency-track.api.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "dependency-track.fullname" . }}
  selector:
    matchLabels:
      {{- include "dependency-track.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dependency-track.api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 1
      serviceAccountName: {{ include "dependency-track.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: apiserver
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          {{- with .Values.api.image }}
          image: "{{ .repository }}:{{ .tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "dependency-track.fullname" . }}-apiserver-config
          ports:
            - name: http
              containerPort: {{ .Values.api.service.containerPort }}
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "dependency-track.pvcName" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
