apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "allure.fullname" . }}-api
  labels:
    {{- include "allure-api.labels" . | nindent 4 }}
data:
  CHECK_RESULTS_EVERY_SECONDS: {{ .Values.updateFrequency | quote }}
  KEEP_HISTORY: {{ .Values.keepHistory | int | quote }}
  TLS: {{ .Values.securityEnabled | int | quote }}
  SECURITY_ENABLED: {{ .Values.securityEnabled | int | quote }}
  MAKE_VIEWER_ENDPOINTS_PUBLIC: {{ .Values.publicViewerEndpoint | int | quote }}
  DEV_MODE: {{ .Values.api.devMode | int | quote }}
