apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "allure.fullname" . }}-ui
  labels:
    {{- include "allure-ui.labels" . | nindent 4 }}
data:
  ALLURE_DOCKER_PUBLIC_API_URL: https://{{ .Values.domain }}