apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "allure.fullname" . }}
  labels:
    {{- include "allure.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "allure.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "allure.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "allure.fullname" . }}
            - secretRef:
                name: {{ include "allure.fullname" . }}
          ports:
            - name: api
              containerPort: 5050
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /allure-docker-service/version
              port: api
          readinessProbe:
            httpGet:
              path: /allure-docker-service/version
              port: api
