apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "allure.fullname" . }}-ui
  labels:
    {{- include "allure-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.ui }}
  selector:
    matchLabels:
      {{- include "allure-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations.ui }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "allure-ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.ui.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-ui
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.ui.repository }}:{{ .Values.image.ui.tag }}"
          imagePullPolicy: {{ .Values.image.ui.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "allure.fullname" . }}-ui
          ports:
            - name: ui
              containerPort: 5252
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /allure-docker-service-ui/version
              port: ui
          readinessProbe:
            httpGet:
              path: /allure-docker-service-ui/version
              port: ui
          resources:
            {{- toYaml .Values.resources.ui | nindent 12 }}
