{{- if .Values.ingress.enabled }}
{{- $fullName := include "allure.fullname" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "allure.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- with .Values.ingress }}
  ingressClassName: {{ default "nginx" .ingressClassName }}
  {{- if .tls }}
  tls:
    - hosts:
        - {{ .hostname | quote }}
      secretName: {{ default (printf "%s-tls" $fullName) .existingSecret }}
  {{- end }}
  rules:
    - host: {{ .hostname | quote }}
      http:
        paths:
          - path: /allure-docker-service/?(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "allure.fullname" . }}-api
                port:
                  name: api
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "allure.fullname" . }}-ui
                port:
                  name: ui
{{- end }}
{{- end }}
