apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.ui.name }}
  labels:
    {{- include "allure-ui.labels" . | nindent 4 }}
  {{- with .Values.service.ui.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  type: {{ .Values.service.ui.type }}
  ports:
    - port: {{ .Values.service.ui.port }}
      targetPort: ui
      protocol: TCP
      name: ui
  selector:
    {{- include "allure-ui.selectorLabels" . | nindent 4 }}
