apiVersion: v1
kind: Service
metadata:
  name: {{ include "allure.fullname" . }}-ui
  labels:
    {{- include "allure-ui.labels" . | nindent 4 }}
  {{- with .Values.ui.service.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: ui
      protocol: TCP
      name: ui
  selector:
    {{- include "allure-ui.selectorLabels" . | nindent 4 }}
