apiVersion: v1
kind: Service
metadata:
  name: {{ include "allure.fullname" . }}-api
  labels:
    {{- include "allure-api.labels" . | nindent 4 }}
  {{- with .Values.api.service.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "allure-api.selectorLabels" . | nindent 4 }}
