apiVersion: v1
kind: Service
metadata:
  name: {{ include "allure.fullname" . }}-api
  labels:
    {{- include "allure.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "allure.selectorLabels" . | nindent 4 }}
