apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.api.name }}
  labels:
    {{- include "allure-api.labels" . | nindent 4 }}
  {{- with .Values.service.api.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "allure-api.selectorLabels" . | nindent 4 }}
