
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "allure.fullname" . }}-api
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: {{ .Values.volume.className }}
  resources:
    {{- toYaml .Values.volume.resources | nindent 4 }}