{{- if and (.Values.volume.enabled) (not .Values.volume.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "allure.fullname" . }}-data
  labels:
    {{- include "allure-api.selectorLabels" . | nindent 4 }}
spec:
{{- with .Values.volume }}
  accessModes:
    {{- toYaml .accessModes | nindent 4 }}
  volumeMode: Filesystem
  storageClassName: {{ .storageClassName }}
  resources:
    requests:
      storage: {{ .size }}
{{- end }}
{{- end }}
