
nameOverride: ""
fullnameOverride: ""

ui:
  replicaCount: 1
  image:
    repository: frankescobar/allure-docker-service-ui
    tag: "7.0.3"
    digest: sha256:b06d1ee48be866d674bf2719df068e0402cee83553bc94bb05f06821bfdb5deb
    pullPolicy: IfNotPresent
  podAnnotations: {}
  podSecurityContext: {}
  resources: {}
  service:
    type: ClusterIP
    port: 80

api:
  replicaCount: 1
  image:
    repository: frankescobar/allure-docker-service
    tag: "2.17.2"
    digest: sha256:849d7776ad0e8b45b2f963875d101520534b0c57885548b481cf4bd88c487e5f
    pullPolicy: IfNotPresent
  podAnnotations: {}
  podSecurityContext: {}
  resources: {}
  service:
    type: ClusterIP
    port: 80

podSecurityContext: {}
  # fsGroup: 2000

keepHistory: true
updateFrequency: NONE

securityEnabled: true
publicViewerEndpoint: false

securityContext:
  runAsUser: 1000
  runAsGroup: 1000

credentials: api-credentials

ingress:
  enabled: false
  tls: false
  existingSecret: ""
  ingressClassName: nginx
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt

hostname: allure-domain.com
