{{- if not .Values.config.existingName }}
{{- $fullName := include "homeassistant.fullname" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-config
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
data:
{{- if .Values.config.values }}
  configuration.yaml: {{ toYaml .Values.config.values | nindent 4 }}
{{- else }}
  configuration.yaml: |
    default_config:
    tts:
      - platform: google_translate
    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml
{{- if .Values.ingress.enabled }}
    http:
      use_x_forwarded_for: true
      cors_allowed_origins:
        - https://{{ .Values.ingress.hostname }}
      # TODO Improve!
      trusted_proxies:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
      ip_ban_enabled: false
      login_attempts_threshold: 5
{{- end }}
{{- if .Values.mysql.install }}
    recorder:
    {{- with .Values.mysql.auth }}
      db_url: {{ printf "mysql://%s:%s@%s-mysql/%s?charset=utf8mb4" .username .password $.Release.Name .database | quote }}
    {{- end }}
{{- end }}
{{- end }}

{{- end }}
