replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.27.2"
  digest: sha256:3536d368b898eef291fb1f6d184a95f8bc1a6f863c48457395aab859fda354d1
  port: 80

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  auth:
    enabled: false
    users: {}
    #  - username: ""
    #    password: ""
    useSecretName: ""
  className: nginx
  annotations: {}
    # kubernetes.io/tls-acme: "true"
  hostname: ""
  tls: false

resources: {}
#  limits:
#    cpu: 400m
#    memory: 100Mi
#  requests:
#    cpu: 10m
#    memory: 10Mi

nodeSelector: {}

tolerations: []

affinity: {}

envFrom: []

readinessProbe:
  enabled: false
  path: "/"
  failureThreshold: 3
  successThreshold: 1
  periodSeconds: 10
  timeoutSeconds: 1

livenessProbe:
  enabled: true
  path: "/"
  failureThreshold: 3
  successThreshold: 1
  periodSeconds: 10
  timeoutSeconds: 1

# -- (string, bool) Additional config in nginx server config definition.
# If false, then ConfigMap won't be mounted
# If string, content will be appended to ConfigMap
configNginx: true

useMemoryStorage: false
git:
  enabled: false
  server: github.com
  user: git
  # kubectl create secret generic --type=kubernetes.io/ssh-auth \
  #   --from-file=ssh-publickey=ssh.pub --from-file=ssh-privatekey=ssh.key \
  #   -n YOURNAMESPACE yourname-sshkey
  sshKeySecret: ""
  repository: ""
  branch: main
  # -- Keep the git directory after cloning. If false, deletes before copying to nginx.
  keep: true
  # -- Number of commits to fetch. 0 indicates all history for all branches and tags.
  # Defaults to 1 (download latest commit only)
  depth: 1
  # -- Move git folder to a subfolder or keep content in main folder.
  # Defaults to empty (use main folder)
  targetDirectory: ""
  updater:
    # -- Add a sidecar container that pulls content from Git.
    # Requires keeping Git folder.
    enabled: false
    # -- Seconds to wait before pulling content again.
    interval: 90

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 8Gi
  mountPath: /data
  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  existingClaim: ""

  ## Data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: null
