apiVersion: v1
kind: Service
metadata:
  name: {{ include "allure-ui.fullname" . }}
  labels:
    {{- include "allure-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ui
      protocol: TCP
      name: ui
  selector:
    {{- include "allure-ui.selectorLabels" . | nindent 4 }}
