apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "librenms.fullname" . }}-syslog
  labels:
    {{- include "librenms.syslog.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.syslog.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "librenms.syslog.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.syslog.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "librenms.syslog.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "librenms.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.syslog.podSecurityContext | nindent 8 }}
      initContainers:
        - name: copy-config
          image: busybox
          command:
            - sh
            - '-c'
            - cp -r /tmp/config/. /data/config/
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /tmp/config
            - name: data
              mountPath: /data
      containers:
        - name: syslog
          securityContext:
            {{- toYaml .Values.syslog.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            {{ include "librenms.environment_ref_default" . | nindent 12 }}
          env:
            - name: SIDECAR_SYSLOGNG
              value: "1"
          lifecycle:
            {{- if .Values.applyPatchPR }}
            postStart:
              exec:
                command:
                  - sh
                  - '-c'
                  - >-
                      for PR_ID in {{ join " " .Values.applyPatchPR }}; do
                        ./scripts/github-apply ${PR_ID};
                      done
            {{- end }}
            preStop:
              exec:
                command:
                  - sh
                  - '-c'
                  - >-
                      s6-svscanctl -q /var/run/s6/services; killall -9 s6-supervise
          ports:
            - name: syslog-tcp
              containerPort: 514
              protocol: TCP
            - name: syslog-udp
              containerPort: 514
              protocol: UDP
          livenessProbe:
            tcpSocket:
              port: syslog-tcp
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: syslog-tcp
            periodSeconds: 20
          resources:
            {{- toYaml .Values.syslog.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
        - name: config
          configMap:
            name: {{ include "librenms.fullname" . }}-config
      {{- with .Values.syslog.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.syslog.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.syslog.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
