{{- $fullName := include "salt.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-alcali" ($fullName) }}
  labels:
    {{- include "salt.master.labels" . | nindent 4 }}
stringData:
  MASTER_MINION_ID: ""
  SECRET_KEY: {{ .Values.alcali.secretKey }}
  ALLOWED_HOSTS: '*'
  {{- $saltRest := printf "%s-rest" ($fullName) }}
  {{- $saltPort := .Values.master.service.ports.https.port }}
  SALT_URL: {{ printf "https://%s:%d" $saltRest ($saltPort | int) }}
  SALT_AUTH: rest
  DB_BACKEND: mysql
  {{- with .Values.mysql }}
  DB_NAME: {{ .auth.database }}
  DB_USER: {{ .auth.username | quote }}
  DB_PASS: {{ .auth.password | quote }}
  DB_HOST: {{ .hostname | default (printf "%s-mysql" ($.Release.Name)) }}
  DB_PORT: {{ .primary.service.ports.mysql | default 3306 | int | quote }}
  {{- end }}
