name: PR Check

on:
  pull_request:

jobs:
  list:
    name: list changes
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.changed-files.outputs.all_modified_files	}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: 'charts/**'
          dir_names: true
          json: true

  check:
    name: Check folder ${{ matrix.path }}
    runs-on: ubuntu-latest
    needs: [list]
    strategy:
      fail-fast: false
      matrix:
        path: ${{ needs.list.outputs.folders }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      - name: Check chart
        working-directory: ${{ matrix.path }}
        run: >
          helm dependency update &&
          helm lint
